# Generated by Django 2.0.6 on 2018-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0002_auto_20180917_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True),
        ),
    ]
