# Generated by Django 2.0.6 on 2018-09-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0004_auto_20180917_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='login_account',
            new_name='nikename',
        ),
    ]
