# Generated by Django 2.0.6 on 2018-09-17 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0006_auto_20180917_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showimg',
            options={'verbose_name': '首页图片', 'verbose_name_plural': '首页图片'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': '交易帖子', 'verbose_name_plural': '交易帖子'},
        ),
        migrations.RemoveField(
            model_name='showimg',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='showimg',
            name='img',
        ),
        migrations.AddField(
            model_name='showimg',
            name='transcation',
            field=models.OneToOneField(default=20180917, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.Transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='indeximg'),
        ),
        migrations.AlterField(
            model_name='showimg',
            name='img_type',
            field=models.IntegerField(choices=[(0, '轮播'), (1, '最热'), (2, '最新')], default=3),
        ),
        migrations.AlterField(
            model_name='showimg',
            name='stat',
            field=models.IntegerField(choices=[(0, '下架'), (1, '上架')], default=1),
        ),
    ]
