# Generated by Django 2.0.6 on 2018-09-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0007_auto_20180917_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(choices=[(0, '梦幻论坛'), (1, '梦幻工具'), (2, '五开概览'), (3, '梦幻金价'), (4, '梦幻其他')])),
                ('stat', models.IntegerField(choices=[(0, '下架'), (1, '上架')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='stat',
            field=models.IntegerField(choices=[(0, '售出'), (1, '上架')], default=1),
        ),
    ]
