# Generated by Django 2.0.6 on 2018-09-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0008_auto_20180918_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightnav',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
