# Generated by Django 2.0.6 on 2018-09-20 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0013_auto_20180920_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolebase',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.Transaction'),
            preserve_default=False,
        ),
    ]
